### ISSUE TITLE
train_data.npy in CAT.py

### ISSUE THREAD

**Issue by Sarah-Xu-08** [eeyhsong/EEG-Conformer#12]
Hi! Thank you for sharing the code!

I have a question about the data you use in CAT visualization. There is one line `data = np.load('./grad_cam/train_data.npy')  ` but I couldn't find the corresponding file. Could you explain what this file is? What kind of data it contained? Thx!

**Comment by eeyhsong** [comment]
hello @Sarah-Xu-08,
You can directly use your data with shape _(batch, feature channel, electrode channel, time samples)_.
Best.

**Comment by Sarah-Xu-08** [comment]
Thank you so much for the reply! It solved my problem!
