### ISSUE TITLE
How should 'Label' look?

### ISSUE THREAD

**Issue by basic0908** [eeyhsong/EEG-Conformer#14]
Hey, I am new to EEG processing.
I am getting an error on 'label' and it seems that labels dont exist.
![image](https://github.com/eeyhsong/EEG-Conformer/assets/100826336/4b150ab3-c7ff-49b9-9df4-27b0b18e7fe3)

I am trying to make a separate file for labels and I would like to know the label should look like.

Thanks in advance

**Comment by eeyhsong** [comment]
@basic0908 hello! It's a 1-D array like (0, 1, 1, 2). It could be used to calculate cross-entropy loss.
