### ISSUE TITLE
Intentionally Calculating this for each forward ??

### ISSUE THREAD

**Issue by vamsikumbuf** [eeyhsong/EEG-Conformer#28]
https://github.com/eeyhsong/EEG-Conformer/blob/f17667d33671725666437b3e447e4363de4a3bce/conformer.py#L115

Here scaling variable is calculated for every forward loop, is this intentional otherwise this can be kept inside the __init__ function right?

**Comment by eeyhsong** [comment]
Thanks for your suggestion, it's really a fixed value.
