### ISSUE TITLE
Need .mat file to run and understand the code

### ISSUE THREAD

**Issue by Maunish-dave** [eeyhsong/EEG-Conformer#3]
Can you please provide an example .mat file for testing the code?
Or a .py file that shows how .gdf files were converted into .mat.

**Comment by eeyhsong** [comment]
@Maunish-dave hello, you can try this code: https://github.com/eeyhsong/EEG-Transformer/blob/main/getData.m and de comment the standardization part.

**Comment by Maunish-dave** [comment]
Got it. Thanks for the link.
