### ISSUE TITLE
The difference between EEG-Transformer and EEG-Conformer

### ISSUE THREAD

**Issue by CharlieHon** [eeyhsong/EEG-Conformer#31]
Thank you for sharing your work! I noticed that you proposed the EEG-Transformer model in  [https://github.com/eeyhsong/EEG-Transformer](url). The EEG-Transformer achieved an accuracy of 82.59% on the 2a dataset, which surpasses the performance of the EEG-Conformer. However, when I attempted to reproduce these results using both models, I obtained a similar accuracy with the EEG-Conformer (around 78%), but only 66.47% with the EEG-Transformer. I would appreciate it if you could clarify the differences between these two models and advise which one I should cite as a reference in my research. I am looking forward to your prompt response.

**Comment by eeyhsong** [comment]
Hello @CharlieHon,

The first version, EEG Transformer,  tried to depend more on self-attention like the vanilla ViT. The performance with the neural network was not okay so we used the signal after the CSP (common spatial pattern) as the input. The Conformer utilized convolution to capture local temporal features of the raw signals, which is a better and end-to-end way. I suggest using the newer one.

Best,
