### ISSUE TITLE
seed的数据集有很多，请问您用的具体是哪个呢？

### ISSUE THREAD

**Issue by tian-2024** [eeyhsong/EEG-Conformer#33]
您好，我下载了seed数据集，但是发现里面有很多，比如 Processed，Extracted_1s, Extract_4s，还有别的什么的，请问您用的是哪个？
另外我看到很多论文会有DE特征啥的，您这篇是只用原数据吗？如果用在那些DE特征上可以吗？

**Comment by eeyhsong** [comment]
@tian-2024 您好。用的是最早版本的seed数据，取了1秒，印象里是重新做了一下预处理。
这篇是试图用原始数据做的，个人感觉DE特征会损失一些信息。但目前看DE的表现是很好的，这也取决于范式。可以再参考下其他文章～

**Comment by tian-2024** [comment]
> @tian-2024 您好。用的是最早版本的seed数据，取了1秒，印象里是重新做了一下预处理。 这篇是试图用原始数据做的，个人感觉DE特征会损失一些信息。但目前看DE的表现是很好的，这也取决于范式。可以再参考下其他文章～

可以~感谢🙏

**Comment by AGXXY** [comment]
> > @tian-2024 您好。用的是最早版本的seed数据，取了1秒，印象里是重新做了一下预处理。 这篇是试图用原始数据做的，个人感觉DE特征会损失一些信息。但目前看DE的表现是很好的，这也取决于范式。可以再参考下其他文章～
> 
> 可以~感谢🙏

哥，gdf转mat那一步可以教我一下吗，1450805943@qq.com
