### ISSUE TITLE
About SEED dataset

### ISSUE THREAD

**Issue by Riptide3** [eeyhsong/EEG-Conformer#5]
Can you please share your preprocessing and training code about the SEED dataset? Especially in the data loading and augmentation part, many parameters are hard-coded, its hard to understand.

**Comment by niwolpert** [comment]
It's not clear to me how the original data sets (for example the .gdf files from the motor imagery task) were transformed into the specific format of the .mat files that are called in the script. I would very much appreciate if you could share either the code for the transformation or the transformed data directly (which the script can be directly called on).

**Comment by 384068026** [comment]
您好，我的研究方向是脑电信号情绪识别，您提到的SEED系列数据集我先前也进行过大量试验，关于本项目作者的另一个项目EEG-Transformer项目我也有所研究，针对您的问题，我似乎有解决方案，但是想与您沟通一下，如您同意，请添加我的QQ：384068026

**Comment by eeyhsong** [comment]
Hello, @Riptide3,
Sorry, the code for SEED has not been prepared well. This part also uses only band-pass filter and standardization for preprocessing, without data augmentation (due to enough data). And we choose 5-fold cross-validation instead of using 9 trials for training and 6 trials for test.

**Comment by eeyhsong** [comment]
Hello, @384068026 
You can directly use Confomer, which is more reasonable than the previous one.

**Comment by 384068026** [comment]
非常感谢您的答复，我想问的问题是seed数据集上进行实验只需要将数据按照1s的时间窗大小来切片然后堆叠成getData.m输出的那个结构就可以了是吗？模型内的参数什么的需要调参吗？然后用kflod来分配数据就可以了吧？您方便提供一些这些代码吗？如果您还未打算开源这一部分，我将自己尝试。非常感谢您的贡献

**Comment by eeyhsong** [comment]
@384068026 您好，是这样的。seed上我没有进行较详细的调参，感兴趣的话您可以尝试一下。这部分没有整理好，暂时不release了，非常抱歉
